[project]
name = "outgy"
version = "0.1.0"
description = "Telegram bot that tracks power outages in Iran via Bargh-e Man (برق من)"
readme = "README.md"
authors = [
    { name = "AliAghaahmadi", email = "itsaliaghaahmadi@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "cryptography>=50.0.0",
    "httpx>=0.28.1",
    "jdatetime>=6.1.0",
    "python-telegram-bot>=22.8",
]

[project.scripts]
outgy = "outgy.__main__:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
